name = "sparkmemory"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Chris Eberly"]
maintainers = ["Chris Eberly <ceberly@users.noreply.github.com>"]
maintainers-logins = ["ceberly"]
[[depends-on]]
gnatprove = "^12.1.1"

[build-switches]
release.runtime_checks = "none"
